// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bookstore.Database;

#nullable disable

namespace bookstore.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20241212163718_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bookstore.Database.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cf3308a-d801-4307-8c2e-79ed0b467d4d"),
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = new Guid("9d981a6c-c173-4b6d-9209-293f571d1e25"),
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = new Guid("0e01c4ab-7cb9-4185-9744-9efd35129641"),
                            Title = "The Return of the King"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
